server:
  port: 8095
spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysqlday20?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    password: 123456
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

mybatis:
  type-aliases-package: cn.kgc.movie.common.entity

logging:
  level:
    cn.kgc.user.server.mapper: debug


redis:
  expire: 300