
server:
  port: 8082

spring:
  application:
    name: user-client
  freemarker:
    cache: false
    suffix: .ftl
    content-type: text/html
    charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/