server:
port: 8094

spring:
application:
name: order-server
datasource:
url: jdbc:mysql://127.0.0.1:3306/mysqlday20?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
driver-class-name: com.mysql.cj.jdbc.Driver
username: root
password: 123456

eureka:
client:
service-url:
defaultZone: http://localhost:8000/eureka/

mybatis:
type-aliases-package: cn.kgc.movie.common.entity

logging:
level:
cn.kgc.order.server.mapper: debug
page:
size: 8

